### ISSUE TITLE
Transform JSON into Another JSON

### ISSUE THREAD

**Issue by ricardojlrufino** [ingon/json-zero#2]
Hi, i have a use case , to create a library to transform a JSON to another JSON like:

Necessary to integrate (large) systems, with many APIs, and that use different dialects..

Is it possible to do this using this lib?

Example:

Input

```
{
    codCli: "Value"
    nCli : "valie"
    addrs: [
        ...
    ]
}
```

Output:

```
{
    codigoClient: "Value"
    nomeCliente : "valie"
    enderecosCliente: [
        ...
    ]
}
```

**Comment by ingon** [comment]
Sure, use a [ContentHandler](https://github.com/ingon/json-zero/blob/master/src/main/java/dev/ingon/json/zero/ContentHandler.java) that does the rewrite as it goes through the data, by overriding `beginObjectEntry`.
